### PR TITLE
Master 0.10.x python3

### PR DESCRIPTION
**Pull request by WarsTime**
Hello. This is a proposition for python3/Kodi Matrix base. I use it at home and it's OK for my usage. But I'm not sure it's completely OK. I didn't use automatic test.

### CODE REVIEW

**Comment by Wintermute0110** [comment]
Hi, thanks for this. The diff is huge because you include a lot of formatting changes, which makes difficult to follow it. What toold did you use for the formatting changes? Can you please make another PR without the formatting changes?

**Comment by WarsTime** [comment]
Sorry. I use Kate (from KDE), it has an option to delete useless spaces when saving.
My new commit should be better, I hope.

**Comment by Wintermute0110** [comment]
No need to be sorry, I was just curios. This tool is useful and I am also a Kate user but didn't used that option.

Again, thanks for your help. I don't know if you had a read to the changelog.txt which contains my current plans for AEL. I would like to release `0.9.10` in python 2 with a few bugfixes and then release `0.10.0` as a python 3 mirror of `0.9.10`. Your work will be very useful. Is it OK to do the following?

1) Let me do the bugfixes in branch `release-0.9.x-python2` and release `0.9.10`. I will use Kate to remove all the unused spaces as you taught me.

2) Once this is done please rebase your PR and do a merge against branch `release-0.10.x-python3`.

Is this OK? Also, currently I am in a very difficult moment in my life and won't have much free time to work on the addons. I will do this ASAP.

**Comment by WarsTime** [comment]
OK. Take the time you need.
I just post in Issues part the zip link of Matrix version, this will allow people who need a Matrix version to wait for the official one.

**Comment by Wintermute0110** [comment]
@WarsTime Thanks for your effort doing this. I will close it now.

**Pull request closed without merging**
